### ISSUE TITLE
HTTP 401 not captured on android

### ISSUE THREAD

**Issue by nconroy** [lazaronixon/react-native-turbolinks#14]
On iOS my authentication view is triggered normally just like in the example. However, on Android, the 401 unauthorised page is shown on the Turbolinks view without being captured by the error handler.

The handleError function is copied directly from the example app and hasn't been changed yet

**Comment by nconroy** [comment]
Some further info: If I don't use startSingleScreenApp and just use visit the error handler works.

**Comment by lazaronixon** [comment]
I faced this problem on my app too. It seems a problem with turbolinks-android. https://github.com/turbolinks/turbolinks-android/issues/91. It hapens because turbolinks needs javascript loaded on the page to trigger the error on native. I solved it responding with a 401 status  with a blank page with only turbolinks.js appended. Take a look on my wiki https://github.com/lazaronixon/react-native-turbolinks/wiki/Devise

**Comment by lazaronixon** [comment]
Correcting myself.... I see this problem today on android 7.1.1 . I will investigate..

**Comment by nconroy** [comment]
This is happening on both the simulator and the device.

**Comment by nconroy** [comment]
The devise fix seems to have worked. 
Instead of just sending the response header and basic html sending them to an error page with Turbolinks included is working.
